version: '3.3'

services:
  mongo:
    image: mongo:4.4
    environment:
      user: process.env.MONGO_INITDB_ROOT_USERNAME,
      password: process.env.MONGO_INITDB_ROOT_PASSWORD,
    ports:
      - 27017:27017
    volumes:
     - ./mongo_data:/data/db